cc_library (
    name = "jni",
    hdrs = [
        "include/jni.h"
    ],
    srcs = [
        "lib/libjvm.so"
    ],
    includes = [
        "include/linux",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

