cc_library (
    name = "libcuckoo",
    hdrs = [
        "libcuckoo/cuckoohash_config.hh",
        "libcuckoo/cuckoohash_map.hh",
        "libcuckoo/cuckoohash_util.hh",
        "libcuckoo/libcuckoo_bucket_container.hh",
    ],
    srcs = [ ],
    includes = [ ".", ],
    deps = [ ],
    copts = [ '-O2', '-Wall', '-std=c++11', '-fopenmp', ],
    linkopts = [ ],
    visibility = ["//visibility:public"],
)

